export const data = [
  {
    id: "1",
    name: "Company Policy Handbook",
    type: "PDF Document",
    size: "2.4 MB",
    uploadedBy: "John Smith",
    uploadDate: "2024-03-15",
    status: "Active",
  },
  {
    id: "2",
    name: "Employee Agreement Template",
    type: "Word Document",
    size: "567 KB",
    uploadedBy: "Sarah Johnson",
    uploadDate: "2024-03-14",
    status: "Active",
  },
  {
    id: "3",
    name: "Building Safety Guidelines",
    type: "PDF Document",
    size: "1.2 MB",
    uploadedBy: "Mike Brown",
    uploadDate: "2024-03-12",
    status: "Pending",
  },
  {
    id: "4",
    name: "Quarterly Financial Report",
    type: "Excel Spreadsheet",
    size: "890 KB",
    uploadedBy: "Emily Davis",
    uploadDate: "2024-03-10",
    status: "Active",
  },
  {
    id: "5",
    name: "Marketing Materials 2024",
    type: "ZIP Archive",
    size: "15.7 MB",
    uploadedBy: "Chris Wilson",
    uploadDate: "2024-03-08",
    status: "Inactive",
  },
]; 